sensor:
    - name: "Next Loadshedding"
      unique_id: "next_loadshedding"
      device_class: timestamp
      state: >
        {% set events = states.sensor.esp_loadshedding_events.attributes.events %}
        {% if events is defined and events %}
          {{ strptime(events[0].start, '%Y-%m-%dT%H:%M:%S%z') }}
        {% else %}
          {{ now() }}
        {% endif %}
    - name: "Minutes to next loadshedding"
      unique_id: "minutes_to_next_loadshedding"
      state: >
        {% set events = states.sensor.esp_loadshedding_events.attributes.events %}
        {% if events is defined and events %}
          {% set esp_day = strptime(events[0].start, '%Y-%m-%dT%H:%M:%S%z').day | int %}
          {% set esp_today = now().day | int %}
          {% if esp_day == esp_today %}
            {{ ((strptime(events[0].start, '%Y-%m-%dT%H:%M:%S%z') - now() ).seconds/60) | int }}
          {% else %}
            {{ 1440 | int}}
          {% endif %}
        {% else %}
          7777
        {% endif %}


      # {% set esp_day = strptime(states.sensor.esp_loadshedding_events.attributes.events[0].start, '%Y-%m-%dT%H:%M:%S%z').day | int%}
      # {% set esp_today = now().day | int %}
      # {% if esp_day == esp_today -%}
      #   {{ ((strptime(states.sensor.esp_loadshedding_events.attributes.events[0].start, '%Y-%m-%dT%H:%M:%S%z') - now() ).seconds/60) | int }}
      # {%- else -%}
      #   {{ 1000 | int}}
      # {%- endif %}
      
      # {{ strptime(states.sensor.esp_loadshedding_events.attributes.events[0].start, '%Y-%m-%dT%H:%M:%S%z') }}
      # {{ ((strptime(states.sensor.esp_loadshedding.attributes.events[0].start, '%Y-%m-%dT%H:%M:%S%z') - now() ).seconds/60) | int }}
        






