sensor:
  - platform: rest
    unique_id: a90af3d0-a949-4b94-b56b-446cd14cfeba
    name: Eskom
    resource: https://loadshedding.eskom.co.za/LoadShedding/GetStatus
    scan_interval: 1800
  
  - platform: rest
    unique_id: a4879ff4-4e88-4072-b842-cae1e9948e06
    name: esp_loadshedding_events
    resource: https://developer.sepush.co.za/business/2.0/area?id=tshwane-13-rooihuiskraal
    headers: 
      token: 38D73705-25CF463C-84C7A4A6-1E3546A6
    json_attributes:
      - events
      - schedule
    scan_interval: 3600
    value_template: "{{ value_json.info.name }}"

  - platform: rest
    unique_id: 23bd0189-fd66-4703-ab9c-8f1f205b2b94
    name: esp_loadshedding_callcount
    resource: https://developer.sepush.co.za/business/2.0/api_allowance
    headers: 
      token: 38D73705-25CF463C-84C7A4A6-1E3546A6
    scan_interval: 3600
    value_template: "{{ value_json.allowance.count }}"

#- platform: rest
#  name: esp_loadshedding_status
#  resource: https://developer.sepush.co.za/business/2.0/status
#  headers: 
#    token: 38D73705-25CF463C-84C7A4A6-1E3546A6
#  json_attributes:
#    - status.eskom
#  scan_interval: 1800
#  value_template: "{{ value_json.stage }}"

#      "status": {
#        "capetown": {
#            "name": "Cape Town",
#            "next_stages": [],
#            "stage": "0",
#            "stage_updated": "2023-12-14T05:00:00.762073+02:00"
#        },
#        "eskom": {
#            "name": "Eskom",
#            "next_stages": [],
#            "stage": "0",
#            "stage_updated": "2023-12-14T05:00:00.762073+02:00"
#        }
#    }

#{
#    "events": [],
#    "info": {
#        "name": "Rooihuiskraal (13)",
#        "region": "City of Tshwane"
#    },
#    "schedule": {
#        "days": [{
#            "date": "2024-01-07",
#            "name": "Sunday",
#            "stages": [
#                ["06:00-08:30"],
#                ["06:00-08:30"],
#                ["06:00-08:30", "22:00-00:30"],
#                ["06:00-08:30", "14:00-16:30", "22:00-00:30"],
#                ["06:00-10:30", "14:00-16:30", "22:00-00:30"],
#                ["00:00-02:30", "06:00-10:30", "14:00-16:30", "22:00-00:30"],
#                ["00:00-02:30", "06:00-10:30", "14:00-16:30", "22:00-00:30"],
#                ["00:00-02:30", "06:00-10:30", "14:00-18:30", "22:00-00:30"]
#            ]
#        }, {
#            "date": "2024-01-08",
#            "name": "Monday",
#            "stages": [
#                ["14:00-16:30"],
#                ["06:00-08:30", "14:00-16:30"],
#                ["06:00-08:30", "14:00-16:30"],
#                ["06:00-08:30", "14:00-16:30", "22:00-00:30"],
#                ["06:00-08:30", "14:00-18:30", "22:00-00:30"],
#                ["06:00-10:30", "14:00-18:30", "22:00-00:30"],
#                ["00:00-02:30", "06:00-10:30", "14:00-18:30", "22:00-00:30"],
#                ["00:00-02:30", "06:00-10:30", "14:00-18:30", "22:00-00:30"]
#            ]
#        }, {
#            "date": "2024-01-09",
#            "name": "Tuesday",
#            "stages": [
#                ["20:00-22:30"],
#                ["12:00-14:30", "20:00-22:30"],
#                ["04:00-06:30", "12:00-14:30", "20:00-22:30"],
#                ["04:00-06:30", "12:00-14:30", "20:00-22:30"],
#                ["04:00-06:30", "12:00-14:30", "20:00-00:30"],
#                ["04:00-06:30", "12:00-16:30", "20:00-00:30"],
#                ["04:00-08:30", "12:00-16:30", "20:00-00:30"],
#                ["00:00-02:30", "04:00-08:30", "12:00-16:30", "20:00-00:30"]
#            ]
#        }, {
#            "date": "2024-01-10",
#            "name": "Wednesday",
#            "stages": [
#                [],
#                ["20:00-22:30"],
#                ["12:00-14:30", "20:00-22:30"],
#                ["04:00-06:30", "12:00-14:30", "20:00-22:30"],
#                ["04:00-06:30", "12:00-14:30", "20:00-22:30"],
#                ["04:00-06:30", "12:00-14:30", "20:00-00:30"],
#                ["04:00-06:30", "12:00-16:30", "20:00-00:30"],
#                ["04:00-08:30", "12:00-16:30", "20:00-00:30"]
#            ]
#        }, {
#            "date": "2024-01-11",
#            "name": "Thursday",
#            "stages": [
#                ["04:00-06:30"],
#                ["04:00-06:30"],
#                ["04:00-06:30", "20:00-22:30"],
#                ["04:00-06:30", "12:00-14:30", "20:00-22:30"],
#                ["04:00-08:30", "12:00-14:30", "20:00-22:30"],
#                ["04:00-08:30", "12:00-14:30", "20:00-22:30"],
#                ["04:00-08:30", "12:00-14:30", "20:00-00:30"],
#                ["04:00-08:30", "12:00-16:30", "20:00-00:30"]
#            ]
#        }, {
#            "date": "2024-01-12",
#            "name": "Friday",
#            "stages": [
#                ["12:00-14:30"],
#                ["04:00-06:30", "12:00-14:30"],
#                ["04:00-06:30", "12:00-14:30"],
#                ["04:00-06:30", "12:00-14:30", "20:00-22:30"],
#                ["04:00-06:30", "12:00-16:30", "20:00-22:30"],
#                ["04:00-08:30", "12:00-16:30", "20:00-22:30"],
#                ["04:00-08:30", "12:00-16:30", "20:00-22:30"],
#                ["04:00-08:30", "12:00-16:30", "20:00-00:30"]
#            ]
#        }, {
#            "date": "2024-01-13",
#            "name": "Saturday",
#            "stages": [
#                ["18:00-20:30"],
#                ["10:00-12:30", "18:00-20:30"],
#                ["02:00-04:30", "10:00-12:30", "18:00-20:30"],
#                ["02:00-04:30", "10:00-12:30", "18:00-20:30"],
#                ["02:00-04:30", "10:00-12:30", "18:00-22:30"],
#                ["02:00-04:30", "10:00-14:30", "18:00-22:30"],
#                ["02:00-06:30", "10:00-14:30", "18:00-22:30"],
#                ["02:00-06:30", "10:00-14:30", "18:00-22:30"]
#            ]
#        }],
#        "source": "http://www.tshwane.gov.za/sites/Departments/Public-works-and-infrastructure/Pages/Load-Shedding.aspx"
#    }
#}
